knative/infra

README.md, prow/README.md, prow/cluster-definitions/README.md, prow/configs/README.md, prow/job-definitions/README.md, prow/jobs/README.md
New READMEs and some migrated info from older ones. Below is proposed layout:
prow/
|- cluster-definitions/
|---- control-plane
|-------- 100-700-*.yaml (move from .)
|---- boskos*.yaml (remove parent folder, keep just the single yaml. This maybe should be moved this to the gcp/boskos folder)
|---- build/
|---- monitoring/
|---- prowjob-crd*.yml (remove parent folder)
|---- Makefile* (moved from ../)
|- job-definitions/ (renamed from jobs_config)
|- jobs/
|- config/
|---- prow-components.yaml (renamed from config.yaml)
|---- hook-plugins.yaml (renamed from plugins.yaml)
|---- labels.yaml (moved from config/label_sync)
|---- testgrid/
|-------- *-testgrid-*.yaml (moved from config/prow/k8s-testgrid)
gcp/
|- (move all infra/gcp files here)
=> Initial repo reorg change

images/prow-tests/Dockerfile, images/prow-tests/cloudbuild.yaml
/cc @kvmware 
The `release-jobs-syncer` job is misconfigured right now and checks out the old repo. The tool needs to be compiled and called with the new repository.
https://github.com/knative/test-infra/pull/3840 needs to run in this repo which means the extra_refs have to be knative/infra and the job needs to look like this:
```yaml
- cron: "0 */2 * * *" # Every other hour
name: ci-knative-prow-jobs-syncer
agent: kubernetes
decorate: true
cluster: prow-build
extra_refs:
- org: knative
repo: infra
base_ref: main
path_alias: knative.dev/infra
annotations:
testgrid-dashboards: utilities
testgrid-tab-name: ci-knative-prow-jobs-syncer
reporter_config:
slack:
channel: knative-productivity
job_states_to_report:
- failure
report_template: '"The prow-jobs-syncer periodic job has failed, please …
```
=> Build release-jobs-syncer as part of the image

prow/jobs/custom/infra.yaml
/cc @kvmware 
The dockerfile's entrypoint was changed recently.
```Dockerfile
FROM golang:1.20.4
ARG TOOL_NAME
RUN GOBIN=/tools go install "knative.dev/toolbox/${TOOL_NAME}@latest"
ENTRYPOINT ["/tools/${TOOL_NAME}"]
```
=> Update the path for `flaky-test-recorder`

prow/jobs/custom/infra.yaml
/cc @kvmware 
The container bugs have been fixed. I manually submitted this prowjob, it is failing for other errors now.
https://prow.knative.dev/view/gs/knative-prow/logs/ci-knative-flakes-resultsrecorder/1666510717148205056
I also bumped the release-jobs-syncer job to pick up the fixes from https://github.com/knative/infra/pull/91
=> Use the prow-tests image for flaky jobs and bump release-jobs-syncer image

prow/jobs/custom/infra.yaml
/cc @kvmware 
Sometime during the repo shuffle, we set the incorrect flags for this job. The job in knative/test-infra has the flags that match this PR.
https://github.com/knative/test-infra/blob/main/prow/jobs/custom/test-infra.yaml#L219
=> Run flaky-test-reporter recorder with the correct flags

images/prow-tests/cloudbuild.yaml
/cc @kvmware 
The cloudbuild changes in #109 were missing an extra flag required to push images.
=> Fix buildx flags

prow/config.yaml
PRs stuck on shellchecks on git submodules.
/assign @pierDipi
(same as https://github.com/knative/test-infra/pull/3846, but test-infra repo is not used anymore)
=> Make Github Actions optional for eventing-istio

prow/jobs/generated/knative/func-main.gen.yaml, prow/jobs_config/knative/func.yaml
Adds a job for func unit tests. Doing this incrementally so that one issue at a time can be debugged.
Working to get knative/func more aligned with the existing test infra
=> chore: add presubmit job for func unit tests

images/prow-tests/Dockerfile, images/tool/Dockerfile
Bump Go version in `prow-tests` before next release per @dprotaso suggestion. 
/cc @dprotaso 
/cc @knative/knative-release-leads
=> chore: Update Go version in prow-tests image

prow/jobs/generated/knative/serving-main.gen.yaml, prow/jobs_config/knative/serving.yaml
**Which issue(s) this PR fixes**:
Belongs to https://github.com/knative/serving/pull/14289, detail: https://github.com/knative/serving/pull/14289#discussion_r1312698605
**What this PR does, why we need it**:
- Adds a new prow job to run performance tests without mako or kperf.
**Additional Notes**
- continuous target will be added later (when https://github.com/knative/serving/pull/14289 is merged)
- mako + kperf targets will be dropped later (when https://github.com/knative/serving/pull/14289 is merged and tests are stable)
=> add new prow target for performance tests

images/prow-tests/Dockerfile, images/tool/Dockerfile
Also fixes the GVM issue we have been seeing.
https://github.com/moovweb/gvm/issues/438
=> Bump go to 1.21

prow/jobs/generated/knative/serving-main.gen.yaml, prow/jobs_config/knative/serving.yaml
**What this PR does, why we need it**:
- Increases the timeout for Serving performance tests
- This is necessary, as I added an additional test case, now the build takes longer than the default 2h
/assign @upodroid
=> increase timeout for performance tests

images/prow-tests/Dockerfile
**What this PR does, why we need it**:
- Adding `envsubst` to prow builder image
- According to the conversation in: https://cloud-native.slack.com/archives/C04LMU0AX60/p1694433180978699?thread_ts=1694422110.571309&cid=C04LMU0AX60
/assign @upodroid 
I hope i got the right place to have `envsubst` in the prow CI runs.
=> add `envsubst` to prow builder image

prow/jobs/generated/knative/serving-main.gen.yaml, prow/jobs_config/knative/serving.yaml
**What this PR does, why we need it**
- With https://github.com/knative/serving/pull/14289 merged, this updates the performance test jobs
- Drops the old mako/kperf jobs
- Adds a new job calling the new script
=> update continuous performance test jobs

images/prow-tests/Dockerfile
glibc compile errors :(
I need to look into how to do `CGO_ENABLED=0` for rust
https://storage.googleapis.com/knative-prow/logs/nightly_kn-plugin-operator_main_periodic/1706246691578974208/build-log.txt
/cc @kvmware @cardil 
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@ Notarizing macOS Binaries for the release @@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@ 2023-09-25 10:18:54.997020338+00:00
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
rcodesign: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by rcodesign)
rcodesign: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by rcodesign)
rcodesign: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by rcodesign)
rcodesign: …
```
=> pin rust to bullseye to compile rcodesign properly

prow/jobs/generated/knative-extensions/eventing-kafka-broker-main.gen.yaml, prow/jobs_config/knative-extensions/eventing-kafka-broker.yaml
These 2 jobs don't need to run every time, devs can trigger them when it's actually needed.
=> Make Loom and KEDA tests on demand tests

prow/jobs/generated/knative-extensions/eventing-kafka-broker-main.gen.yaml, prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.10.gen.yaml, prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.11.gen.yaml, prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.9.gen.yaml, prow/jobs_config/knative-extensions/eventing-kafka-broker-release-1.10.yaml, prow/jobs_config/knative-extensions/eventing-kafka-broker-release-1.11.yaml, prow/jobs_config/knative-extensions/eventing-kafka-broker-release-1.9.yaml, prow/jobs_config/knative-extensions/eventing-kafka-broker.yaml
Fixes
This PR adds nightly CI testing job for kafka-broker on ppc64le hardware
=> Support added for kafka-broker on ppc64le

images/prow-tests/Dockerfile, images/tool/Dockerfile
To have infra ready in response to https://nvd.nist.gov/vuln/detail/CVE-2023-44487.
/cc @knative/productivity-leads 
/cc @knative/security-wg-leads
=> Bump Go verions to latest patch release

.gitignore, prow/cluster/gitops/apps/eso-prow-build.yaml, prow/cluster/gitops/apps/eso-prow.yaml, prow/cluster/gitops/apps/eso-trusted.yaml, prow/cluster/gitops/bootstrap/kustomization.yaml, prow/cluster/monitoring/chart/Chart.lock, prow/cluster/monitoring/chart/Chart.yaml, prow/cluster/monitoring/chart/values.yaml
I upgraded all the clusters to 1.25 and bumped ArgoCD to 2.9
I'm going to keep upgrading the Kubernetes clusters to 1.27 by the end of this week.
=> Bump argocd, Grafana and ESO

images/prow-tests/Dockerfile, images/tool/Dockerfile
The newer patch version of Golang should fix the issue with license check. 
Reported here as well: https://cloud-native.slack.com/archives/C04LKEZUXEE/p1700817496481049
**1.21.3**
```
➜  client git:(auto-updates/update-deps-main) eval "$(gvm 1.21.3)"
➜  client git:(auto-updates/update-deps-main) go-licenses check ./...
E1129 09:59:30.412368   20088 library.go:117] Package errors does not have module info. Non go modules projects are no longer supported. For feedback, refer to https://github.com/google/go-licenses/issues/128.
E1129 09:59:30.412515   20088 library.go:117] Package fmt does not have module info. Non go modules projects are no longer supported. For feedback, refer to https://github.com/google/go-licenses/issues/128.
E1129 09:59:30.414523   20088 library.go:117] Package bytes …
```
=> Bump Golang to latest patch release

images/prow-tests/Dockerfile, images/tool/Dockerfile
To address https://pkg.go.dev/vuln/GO-2023-2382.
/cc @dprotaso @evankanderson @upodroid
=> Bump Golang to 1.21.5

prow/jobs/generated/knative/serving-main.gen.yaml, prow/jobs_config/knative/serving.yaml
Fixes #287
I think there's something in the environment overrides that caused `.base.yaml` to not apply for Serving, but this seems to have fixed it.  I assumed we'd want any further patch releases on the existing lines to get signatures + attestations, so I updates the existing releases as well.
=> Turn on signing and attestation for serving

prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.10.gen.yaml, prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.11.gen.yaml, prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.12.gen.yaml, prow/jobs_config/knative-extensions/eventing-kafka-broker-release-1.10.yaml, prow/jobs_config/knative-extensions/eventing-kafka-broker-release-1.11.yaml, prow/jobs_config/knative-extensions/eventing-kafka-broker-release-1.12.yaml
- Updating the image tag for Eventing Kafka Broker release, to use the image with jdk20
/cc @upodroid  @pierDipi @Cali0707
=> Rollback to jdk20 for EKB

prow/jobs/generated/knative-extensions/eventing-kafka-broker-main.gen.yaml, prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.11.gen.yaml, prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.12.gen.yaml, prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.13.gen.yaml, prow/jobs/generated/knative-extensions/eventing-kafka-release-1.11.gen.yaml, prow/jobs/generated/knative-extensions/eventing-kafka-release-1.12.gen.yaml, prow/jobs/generated/knative-extensions/eventing-kafka-release-1.13.gen.yaml, prow/jobs/generated/knative-extensions/kn-plugin-event-main.gen.yaml, prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.11.gen.yaml, prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.12.gen.yaml, prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.13.gen.yaml, prow/jobs/generated/knative/client-main.gen.yaml, prow/jobs/generated/knative/client-release-1.11.gen.yaml, prow/jobs/generated/knative/client-release-1.12.gen.yaml, prow/jobs/generated/knative/client-release-1.13.gen.yaml, prow/jobs/generated/knative/eventing-main.gen.yaml, prow/jobs/generated/knative/eventing-release-1.11.gen.yaml, prow/jobs/generated/knative/eventing-release-1.12.gen.yaml, prow/jobs/generated/knative/eventing-release-1.13.gen.yaml, prow/jobs/generated/knative/operator-main.gen.yaml, prow/jobs/generated/knative/operator-release-1.11.gen.yaml, prow/jobs/generated/knative/operator-release-1.12.gen.yaml, prow/jobs/generated/knative/operator-release-1.13.gen.yaml, prow/jobs/generated/knative/serving-main.gen.yaml, prow/jobs/generated/knative/serving-release-1.11.gen.yaml, prow/jobs/generated/knative/serving-release-1.12.gen.yaml, prow/jobs/generated/knative/serving-release-1.13.gen.yaml, prow/jobs_config/.base.yaml
This is the PR to remove the KO_FLAG --insecure-repository. This flag when supplied along with platform flag cerating issues building the images in knative/eventing. We have moved from self-hosted registry to IBM cloud container registry hence we don't need the flag anymore.
=> [s390x]: Moving to secure KO_DOCKRE_REPO for s390x arch

images/prow-tests/Dockerfile
I dropped the 'previous' version because now with the go `toolchain` directive in theory each repo can pin the specific library (toolchain) version they want
=> bump go version

prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.13.gen.yaml, prow/jobs_config/knative-extensions/eventing-kafka-broker-release-1.13.yaml
Currently, we are unable to make a patch release on EKB 1.13 because the prow image contains the wrong cosign version. This PR updates the prow image to include the newer cosign version
=> bump: ekb release-1.13 now uses updated base image

prow/jobs/generated/knative/serving-main.gen.yaml, prow/jobs_config/knative/serving.yaml
- add periodic prow job for testing serving + contour + gateway-api
- rename periodic prow job for serving + gateway-api + istio from `gateway-api-latest` to `gateway-api-istio`
Fixes https://github.com/knative/serving/issues/14983
=> add periodic prow job for testing serving + contour + gateway-api

prow/autobump-config/knative.yaml
https://github.com/kubernetes/test-infra/issues/31728#issuecomment-2048438546
https://prow.knative.dev/view/gs/knative-prow/logs/ci-knative-prow-auto-bumper-for-auto-deploy/1782428045601148928
We don't release the images any more with the same hashes(some like in k/test-infra and prow lives in k-sigs/prow).
/cc @cardil
=> Fix consistentimageexceptions

prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.14.gen.yaml, prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.14.gen.yaml, prow/jobs/generated/knative/client-release-1.14.gen.yaml, prow/jobs/generated/knative/eventing-release-1.14.gen.yaml, prow/jobs/generated/knative/operator-release-1.14.gen.yaml, prow/jobs/generated/knative/serving-release-1.14.gen.yaml, prow/jobs_config/knative-extensions/eventing-kafka-broker-release-1.14.yaml, prow/jobs_config/knative-extensions/kn-plugin-event-release-1.14.yaml, prow/jobs_config/knative/client-release-1.14.yaml, prow/jobs_config/knative/eventing-release-1.14.yaml, prow/jobs_config/knative/operator-release-1.14.yaml, prow/jobs_config/knative/serving-release-1.14.yaml
Which issue(s) this PR fixes:
Fixes
PR to add release 1.14 jobs on ppc64le
=> [ppc64le]: add ppc64le specific prow job config for release-1.14

prow/jobs/generated/knative/serving-main.gen.yaml, prow/jobs_config/knative/serving.yaml
- Needed by https://github.com/knative/serving/pull/15066
- Later we can remove completely the net-certmanager jobs. This is the first PR ofmoving stuff.
- Builds, unit tests etc are covered by the serving jobs.
=> Move tests from net-certmanager to serving

prow/jobs/generated/knative/serving-main.gen.yaml, prow/jobs_config/knative/serving.yaml
**Which issue(s) this PR fixes**:
Fixes https://github.com/knative/serving/issues/15274
**What this PR does, why we need it**:
- Fixes istio build config (no-mesh build should have --no-mesh)
=> Fix istio no-mesh build command

images/prow-tests/Dockerfile
Needed for Backstage plugin tests
Fixes
=> Install NodeJS in Prow image

prow/cluster/build/boskos-janitor.yaml
boskos janitor seems to be OOMing
=> use 4 replicas for boskos janitor

prow/jobs/generated/knative-extensions/backstage-plugins-main.gen.yaml, prow/jobs_config/knative-extensions/backstage-plugins.yaml
=> Prow build tests for Backstage stuff

prow/autobump-config/knative.yaml, prow/cluster/control-plane/400-crier.yaml, prow/cluster/control-plane/400-deck.yaml, prow/cluster/control-plane/400-ghproxy.yaml, prow/cluster/control-plane/400-hook.yaml, prow/cluster/control-plane/400-horologium.yaml, prow/cluster/control-plane/400-prow-controller-manager.yaml, prow/cluster/control-plane/400-sinker.yaml, prow/cluster/control-plane/400-tide.yaml, prow/cluster/control-plane/500-cherrypicker.yaml, prow/cluster/control-plane/500-needs-rebase.yaml, prow/cluster/control-plane/500-status-reconciler.yaml, prow/cluster/trusted/ghproxy.yaml, prow/config.yaml, prow/jobs/custom/autobump-flaky-test-reporter.yaml, prow/jobs/custom/autobump-prow-tests.yaml, prow/jobs/custom/autobump-prow.yaml, prow/jobs/custom/autodeploy-prow.yaml, prow/jobs/custom/branchprotector.yaml, prow/jobs/custom/infra.yaml, prow/jobs/custom/label-sync.yaml, prow/jobs/custom/peribolos.yaml, prow/jobs/run_job.sh
https://github.com/kubernetes/test-infra/pull/33210
Prow has been out of date because Kubernetes changed the prow image location.
The bumper should run successfully on the next run
bumper job: https://prow.knative.dev/job-history/gs/knative-prow/logs/ci-knative-prow-auto-bumper-for-auto-deploy
=> switch to the new prow image registry

config/Makefile, prow/jobs/custom/infra.yaml
- Use testgrid's configurator image from gcr.io registry
Address issue described in: https://github.com/knative/infra/pull/520#issuecomment-2379238805
/cc @upodroid in case this's actual source of latest image for testgrid's configurator.
=> Use testgrid's configurator image from gcr.io registry

infra/gcp/dns/redirect/Makefile
stats.knative.dev points to the old knative.teststats.cncf.io. The new domain is knative.devstats.cncf.io.
=> Update link to devstats

prow/jobs/generated/knative/serving-release-1.15.gen.yaml, prow/jobs_config/knative/serving-release-1.15.yaml
Was missing in an earlier commit
=> add serving 1.15 release job

prow/jobs/custom/peribolos.yaml
Fixes #662 
- Adjust peribolos gh api rps
Still double the values of peribolos defaults. Let me know if you think we should go with default, or there's different issue e.g. with tokens.
https://github.com/kubernetes-sigs/prow/blob/main/cmd/peribolos/main.go#L41-L42
/cc @upodroid @cardil @dprotaso
=> Adjust peribolos gh api rps

prow/jobs/custom/peribolos.yaml
- :bug: Bump timeout for CI peribolos to 4h
Should fix issues like https://prow.knative.dev/view/gs/knative-prow/logs/ci-knative-extensions-peribolos/1929946357959757824
Related to https://github.com/knative/infra/issues/662
Follow up on https://github.com/knative/infra/pull/665
=> :bug: Bump timeout for CI peribolos to 4h

prow/jobs/custom/peribolos.yaml
Seems like one user who hadn't accepted the github invite was causing peribolos to fail. I've removed that user in the community repo.
This reverts commit f18e3ea45dd8537feb9b7972d59509a339621b64.
Revert log level back to info.
/assign @upodroid @cardil
=> Revert "bump peribolos log level to debug (#698)"
