knative/infra

.github/pull-request-template.md

Add template for PRs

---

CODE_OF_CONDUCT.md

Fixes https://github.com/knative/infra/issues/10

CODE_OF_CONDUCT update

---

prow/config.yaml
prow/jobs/custom/autobump-flaky-test-reporter.yaml
prow/jobs/custom/autobump-prow-tests.yaml
prow/jobs/custom/autobump-prow.yaml
prow/jobs/custom/autodeploy-prow.yaml
prow/jobs/custom/branchprotector.yaml
prow/jobs/custom/label-sync.yaml

Point infra jobs to the new Infra repo

---

prow/cluster/gitops/apps/monitoring.yaml
prow/cluster/gitops/apps/prow-build.yaml
prow/cluster/gitops/apps/prow-trusted.yaml
prow/cluster/gitops/apps/prow.yaml
prow/cluster/gitops/apps/shared.yaml
prow/cluster/gitops/bootstrap/apps.yaml
prow/cluster/gitops/bootstrap/kustomization.yaml
prow/jobs/custom/test-infra.yaml

Upgrade ArgoCD and point the apps to the new repo

---

prow/autobump-config/knative-flaky-test-reporter.yaml
prow/autobump-config/knative-prow-tests.yaml
prow/autobump-config/knative.yaml
prow/jobs/custom/branchprotector.yaml
prow/plugins.yaml

Enable config-updater for the new repo

---

prow/autobump-config/knative-flaky-test-reporter.yaml
prow/autobump-config/knative-prow-tests.yaml
prow/jobs/custom/infra.yaml

Update the image-bumper config to use the new image location

---

images/prow-tests/Dockerfile
prow/jobs/custom/infra.yaml

/cc @kvmware 
I'll clean up the makefiles and dockerfiles in a separate PR after the jobs for it is gone.

Build `flaky-test-reporter` in the prow-tests image

---

prow/jobs/generated/knative/func-main.gen.yaml
prow/jobs_config/knative/func.yaml

Adds unit and integration test config func. See: https://github.com/knative/func/pull/1808

chore: add unit and integration test config for func

---

images/prow-tests/Dockerfile
images/prow-tests/cloudbuild-test.yaml
images/prow-tests/cloudbuild.yaml
images/simple-image.mk

/cc @pierDipi @lance 
func jobs want to use Java 17

Bump java to 17 and install it from temurin/ecplise

---

prow/jobs/generated/knative-sandbox/kn-plugin-event-main.gen.yaml
prow/jobs/generated/knative-sandbox/kn-plugin-event-release-1.10.gen.yaml
prow/jobs/generated/knative-sandbox/kn-plugin-event-release-1.9.gen.yaml
prow/jobs_config/knative-sandbox/kn-plugin-event-release-1.10.yaml
prow/jobs_config/knative-sandbox/kn-plugin-event-release-1.9.yaml
prow/jobs_config/knative-sandbox/kn-plugin-event.yaml

This PR adds nightly CI testing job for knative-sandbox/kn-plugin-event on ppc64le hardware

Support added for kn-plugin-event on ppc64le

---

prow/jobs/generated/knative-sandbox/kn-plugin-event-main.gen.yaml
prow/jobs/generated/knative-sandbox/kn-plugin-event-release-1.10.gen.yaml
prow/jobs/generated/knative-sandbox/kn-plugin-event-release-1.9.gen.yaml
prow/jobs_config/knative-sandbox/kn-plugin-event-release-1.10.yaml
prow/jobs_config/knative-sandbox/kn-plugin-event-release-1.9.yaml
prow/jobs_config/knative-sandbox/kn-plugin-event.yaml

Fixes
This PR updates the `SSL_CERT_FILE` variable path used in kn-plugin-event tests

SSL_CERT_FILE variable path modified for kn-plugin-event

---

prow/config.yaml

allow functions leads to rerun prowjobs

---

images/prow-tests/Dockerfile

Fixes
/cc @houshengbo @kvmware 
We can do the following:
- Create a helm chart .tgz as part of the release process.
- Copy the tgz file to knative/charts, use `cr` to publish it and host the chart there.

Add `cr` and `helm` cli tools

---

.github/dependabot.yml

Hopefully this will bypass the ok-to-test as well

Auto merge dependabot updates

---

prow/jobs/generated/knative-extensions/kn-plugin-event-main.gen.yaml
prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.10.gen.yaml
prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.11.gen.yaml
prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.9.gen.yaml
prow/jobs/generated/knative/client-main.gen.yaml
prow/jobs/generated/knative/client-release-1.10.gen.yaml
prow/jobs/generated/knative/client-release-1.11.gen.yaml
prow/jobs/generated/knative/client-release-1.9.gen.yaml
prow/jobs/generated/knative/eventing-main.gen.yaml
prow/jobs/generated/knative/eventing-release-1.10.gen.yaml
prow/jobs/generated/knative/eventing-release-1.11.gen.yaml
prow/jobs/generated/knative/eventing-release-1.9.gen.yaml
prow/jobs/generated/knative/operator-main.gen.yaml
prow/jobs/generated/knative/operator-release-1.10.gen.yaml
prow/jobs/generated/knative/operator-release-1.11.gen.yaml
prow/jobs/generated/knative/operator-release-1.9.gen.yaml
prow/jobs/generated/knative/serving-main.gen.yaml
prow/jobs/generated/knative/serving-release-1.10.gen.yaml
prow/jobs/generated/knative/serving-release-1.11.gen.yaml
prow/jobs/generated/knative/serving-release-1.9.gen.yaml
prow/jobs_config/.base.yaml
prow/jobs_config/knative/serving-release-1.10.yaml
prow/jobs_config/knative/serving-release-1.11.yaml
prow/jobs_config/knative/serving-release-1.9.yaml
prow/jobs_config/knative/serving.yaml

PR to modify the registry configs to use nip.io based dns

Modified the registry configs to use nip.io based dns

---

prow/jobs/generated/knative-extensions/kn-plugin-event-main.gen.yaml
prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.10.gen.yaml
prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.11.gen.yaml
prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.9.gen.yaml
prow/jobs/generated/knative/client-main.gen.yaml
prow/jobs/generated/knative/client-release-1.10.gen.yaml
prow/jobs/generated/knative/client-release-1.11.gen.yaml
prow/jobs/generated/knative/client-release-1.9.gen.yaml
prow/jobs/generated/knative/eventing-main.gen.yaml
prow/jobs/generated/knative/eventing-release-1.10.gen.yaml
prow/jobs/generated/knative/eventing-release-1.11.gen.yaml
prow/jobs/generated/knative/eventing-release-1.9.gen.yaml
prow/jobs/generated/knative/operator-main.gen.yaml
prow/jobs/generated/knative/operator-release-1.10.gen.yaml
prow/jobs/generated/knative/operator-release-1.11.gen.yaml
prow/jobs/generated/knative/operator-release-1.9.gen.yaml
prow/jobs/generated/knative/serving-main.gen.yaml
prow/jobs/generated/knative/serving-release-1.10.gen.yaml
prow/jobs/generated/knative/serving-release-1.11.gen.yaml
prow/jobs/generated/knative/serving-release-1.9.gen.yaml
prow/jobs_config/.base.yaml

This PR modifies the KO_DOCKER_REPO to na.artifactory.swg-devops.com/artifactory/sys-linux-power-team-ftp3distro-docker-images-docker-local/knative/

KO_DOCKER repo modified

---

prow/plugins.yaml

/cc @kvmware 
This feature was introduced in https://github.com/kubernetes/test-infra/pull/24978

always trust dependabot PRs

---

prow/jobs/generated/knative-extensions/eventing-kafka-broker-main.gen.yaml
prow/jobs_config/knative-extensions/eventing-kafka-broker.yaml

Fixes https://github.com/knative-extensions/eventing-kafka-broker/issues/3067
/hold until after https://github.com/knative-extensions/eventing-kafka-broker/pull/3322 is merged

Added KEDA reconciler test to ekb

---

prow/cluster/build/secrets.yaml

Fixes
This PR adds a secret named vm-script into ppc64le-cluster secret store

Add a secret into ppc64le-cluster secret store

---

prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.12.gen.yaml
prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.12.gen.yaml
prow/jobs/generated/knative/client-release-1.11.gen.yaml
prow/jobs/generated/knative/client-release-1.12.gen.yaml
prow/jobs/generated/knative/eventing-release-1.11.gen.yaml
prow/jobs/generated/knative/eventing-release-1.12.gen.yaml
prow/jobs/generated/knative/operator-release-1.11.gen.yaml
prow/jobs/generated/knative/operator-release-1.12.gen.yaml
prow/jobs/generated/knative/serving-release-1.11.gen.yaml
prow/jobs/generated/knative/serving-release-1.12.gen.yaml
prow/jobs_config/knative-extensions/eventing-kafka-broker-release-1.12.yaml
prow/jobs_config/knative-extensions/kn-plugin-event-release-1.12.yaml
prow/jobs_config/knative/client-release-1.11.yaml
prow/jobs_config/knative/client-release-1.12.yaml
prow/jobs_config/knative/eventing-release-1.11.yaml
prow/jobs_config/knative/eventing-release-1.12.yaml
prow/jobs_config/knative/operator-release-1.11.yaml
prow/jobs_config/knative/operator-release-1.12.yaml
prow/jobs_config/knative/serving-release-1.11.yaml
prow/jobs_config/knative/serving-release-1.12.yaml

Fixes
PR to add release 1.12 jobs on ppc64le

Add release 1.12 jobs on ppc64le

---

prow/jobs/generated/knative/serving-main.gen.yaml
prow/jobs_config/knative/serving.yaml

Follow-up for https://github.com/knative/serving/pull/14482
**Which issue(s) this PR fixes**:
Fixes https://github.com/knative/serving/issues/14369

use renamed script and param for external-domain-tls

---

prow/autobump-config/knative-prow-tests.yaml
prow/jobs/generated/knative-extensions/eventing-kafka-broker-main.gen.yaml
prow/jobs/generated/knative-extensions/eventing-kafka-release-1.10.gen.yaml
prow/jobs/generated/knative-extensions/eventing-kafka-release-1.11.gen.yaml
prow/jobs/generated/knative-extensions/eventing-kafka-release-1.12.gen.yaml
prow/jobs_config/knative-extensions/eventing-kafka-broker.yaml
prow/jobs_config/knative-extensions/eventing-kafka-release-1.10.yaml
prow/jobs_config/knative-extensions/eventing-kafka-release-1.11.yaml
prow/jobs_config/knative-extensions/eventing-kafka-release-1.12.yaml

@Cali0707 @matzew 
This might work

Skip bumping EKB images

---

config/prow/k8s-testgrid/k8s-testgrid.yaml
prow/jobs/generated/knative-extensions/backstage-plugins-main.gen.yaml
prow/jobs_config/knative-extensions/backstage-plugins.yaml

Fixes
Add release config for backstage-plugins

Add release config for backstage-plugins

---

prow/config.yaml

allow knative-admin gh group to rerun jobs

---

prow/jobs/generated/knative-extensions/eventing-kafka-broker-main.gen.yaml
prow/jobs/generated/knative-extensions/kn-plugin-event-main.gen.yaml
prow/jobs/generated/knative/client-main.gen.yaml
prow/jobs/generated/knative/eventing-main.gen.yaml
prow/jobs/generated/knative/operator-main.gen.yaml
prow/jobs/generated/knative/serving-main.gen.yaml
prow/jobs_config/knative-extensions/eventing-kafka-broker.yaml
prow/jobs_config/knative-extensions/kn-plugin-event.yaml
prow/jobs_config/knative/client.yaml
prow/jobs_config/knative/eventing.yaml
prow/jobs_config/knative/operator.yaml
prow/jobs_config/knative/serving.yaml

Reverts knative/infra#356
This change should be made only after an agreement is made on this subject
It is under active discussion in #344 and no agreement was made till now.

Revert "drop s390x/ppc CI jobs from main branches"

---

prow/jobs/generated/knative-extensions/eventing-kafka-broker-main.gen.yaml
prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.12.gen.yaml
prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.13.gen.yaml
prow/jobs/generated/knative-extensions/kn-plugin-event-main.gen.yaml
prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.12.gen.yaml
prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.13.gen.yaml
prow/jobs/generated/knative/client-main.gen.yaml
prow/jobs/generated/knative/client-release-1.12.gen.yaml
prow/jobs/generated/knative/client-release-1.13.gen.yaml
prow/jobs/generated/knative/eventing-main.gen.yaml
prow/jobs/generated/knative/eventing-release-1.12.gen.yaml
prow/jobs/generated/knative/eventing-release-1.13.gen.yaml
prow/jobs/generated/knative/operator-main.gen.yaml
prow/jobs/generated/knative/operator-release-1.12.gen.yaml
prow/jobs/generated/knative/operator-release-1.13.gen.yaml
prow/jobs/generated/knative/serving-main.gen.yaml
prow/jobs/generated/knative/serving-release-1.12.gen.yaml
prow/jobs/generated/knative/serving-release-1.13.gen.yaml
prow/jobs_config/.base.yaml

Which issue(s) this PR fixes:
Fixes:
docker config env variable for ppc64le jobs

docker_config env variable added for ppc64le jobs

---

prow/jobs/generated/knative/serving-main.gen.yaml
prow/jobs_config/knative/serving.yaml

- add prow job to test gateway api and contour
Part of https://github.com/knative/serving/issues/14983

add prow job to test gateway api and contour

---

prow/jobs/generated/knative-extensions/net-gateway-api-main.gen.yaml
prow/jobs_config/knative-extensions/net-gateway-api.yaml

- make tests for contour in net-gateway-api mandatory for every PR

Make tests for contour in net-gateway-api mandatory

---

prow/jobs/generated/knative/serving-main.gen.yaml
prow/jobs_config/knative/serving.yaml

Fixes https://github.com/knative/serving/issues/15236

Add back certmanager tests

---

prow/jobs/generated/knative-extensions/net-gateway-api-main.gen.yaml
prow/jobs_config/knative-extensions/net-gateway-api.yaml

Adding jobs that'll exercise adding support for envoy gateway
Part of https://github.com/knative-extensions/net-gateway-api/issues/566

[net-gateway-api] add envoy gateway presubmits

---

prow/jobs/generated/knative-extensions/net-gateway-api-main.gen.yaml
prow/jobs_config/knative-extensions/net-gateway-api.yaml

net-gateway-api - tweak envoy gateway jobs

---

images/prow-tests/Dockerfile

Fixes https://cloud-native.slack.com/archives/C04LY4M2G49/p1721635801546009
- :bug: Set GOTOOLCHAIN=local
/kind bug
/cc @ReToCode

:bug: Set GOTOOLCHAIN=local

---

prow/jobs/generated/knative-extensions/backstage-plugins-main.gen.yaml
prow/jobs_config/knative-extensions/backstage-plugins.yaml

Use new prow-tests image in Backstage tests

---

images/prow-tests/Dockerfile

Related https://github.com/knative/actions/pull/236

:broom: Update Go to 1.23.3

---

prow/jobs/generated/knative-extensions/eventing-integrations-main.gen.yaml
prow/jobs_config/knative-extensions/eventing-integrations.yaml

Related to https://github.com/knative/release/issues/349
- Add release job for eventing-integrations repo
/cc @matzew @knative/productivity-leads

Add release job config for eventing-integrations

---

prow/jobs/generated/knative-extensions/eventing-integrations-main.gen.yaml
prow/jobs_config/knative-extensions/eventing-integrations.yaml

Add build tests for eventing-integrations

---

prow/jobs/generated/knative-extensions/eventing-integrations-main.gen.yaml
prow/jobs_config/knative-extensions/eventing-integrations.yaml

We need DinD in all jobs (in build-tests was missing)

Add DinD for eventing-integration 

---

images/prow-tests/Dockerfile

As per title
See https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative-extensions_eventing-integrations/67/build-tests_eventing-integrations_main/1890077893631938560

Fix error '/etc/init.d/docker: 62: ulimit: error setting limit'

---

images/prow-tests/Dockerfile

Pairs with - https://github.com/knative/actions/pull/247

bump go to 1.24.1 and bump other deps

---

prow/jobs/custom/peribolos.yaml

Fixes
A follow-up to #663. 
Sorry, I haven't check the whole file properly, `postsubmit` jobs are more of an issue actually.
/cc @cardil @upodroid @dprotaso

Adjust peribolos gh api rps in postsubmit jobs

---

prow/jobs/custom/peribolos.yaml

Unblocks - https://github.com/knative/community/pull/1700

bump removal delta so we can purge inactive users

---

prow/cluster/control-plane/rbac.yaml

Fixes: https://github.com/knative/infra/issues/222

allow tests to access pod logs

---

prow/config.yaml

automatically merge dependabot changes
